[package]
name = "apple_like_avatar_generator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.11.1"
image = "0.25.10"
md5 = "0.8.1"
regex = "1.13.1"
takumi = "2.4.2"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
