// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `generate`, `get_gradient_colors`, `get_name_to_display`

Future<Uint8List> generateWithName(String name) =>
    RustLib.instance.api.crateApiCoreGenerateWithName(name: name);

Future<Uint8List> generateWithFirstNameLastName(
  String firstName,
  String lastName,
) => RustLib.instance.api.crateApiCoreGenerateWithFirstNameLastName(
  firstName: firstName,
  lastName: lastName,
);
